name: Caller Workflow testing testing

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  trigger-reusable-workflow:
    uses: GHA-Calling-Repo/.github/workflows/called.yaml@main
        
